# Generated by Django 4.1.3 on 2022-11-23 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_comment_like_users_delete_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
